CREATE DATABASE IF NOT EXISTS "Registrys";
-- CREATE DATABASE IF NOT EXISTS "ManutencaoPreditiva";
-- CREATE DATABASE IF NOT EXISTS "OrderServiceDb";
-- CREATE DATABASE IF NOT EXISTS "UserServiceDb";
-- CREATE DATABASE IF NOT EXISTS "LogsDb";
