FROM node:18-alpine

WORKDIR /app

COPY src/client/iot-dashboard/package*.json ./

RUN npm ci

COPY src/client/iot-dashboard/ .

WORKDIR /app/src/client/iot-dashboard

EXPOSE 8080

CMD ["npm", "run", "dev"]
