FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY ./src/api/IoTDataApi/IoTDataApi.csproj ./api/
RUN dotnet restore ./api/IoTDataApi.csproj

COPY ./src/api/IoTDataApi/ ./api/

WORKDIR /src/api
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app

RUN mkdir -p /app/simulator

COPY --from=build /app/publish .

EXPOSE 5000

ENTRYPOINT ["dotnet", "IoTDataApi.dll"]
