FROM python:3.12-slim

WORKDIR /app

COPY src/simulator/sensor_simulator.py .
COPY src/simulator/subscriber.py .

RUN pip install --no-cache-dir paho-mqtt

ARG CMD="sensor_simulator.py"
ENV CMD=${CMD}

ENV MQTT_HOST=mosquitto
ENV MQTT_PORT=1883

CMD ["sh", "-c", "python $CMD"]
